# file: tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed | Debian
  ansible.builtin.apt:
    name: libpq-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the development headers are installed | RedHat
  ansible.builtin.yum:
    name:
      - "postgresql{{ postgresql_version_terse }}-libs"
      - "postgresql{{ postgresql_version_terse }}-devel"
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "yum" and ansible_os_family == "RedHat"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the development headers are installed | Fedora
  ansible.builtin.dnf:
    name:
      - "postgresql{{ postgresql_version_terse }}-libs"
      - "postgresql{{ postgresql_version_terse }}-devel"
    state: present
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Fedora"
  notify:
    - restart postgresql
