# file: tasks/extensions/extra_packages.yml

- include_vars: "../../vars/extra_packages.yml"

# keys

- name: PostgreSQL | Extensions | Add repo keys | apt
  ansible.builtin.apt_key:
    id: "{{ item.value.id }}"
    url: "{{ item.value.url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/{{ item.value.id }}.gpg
  loop: "{{ postgresql_ext_extra_packages.apt_keys | default({}) | dict2items  }}"
  when:
    - postgresql_ext_extra_packages is defined
    - ansible_os_family == "Debian"

# repositories

- name: PostgreSQL | Extensions | Add repos | apt
  ansible.builtin.apt_repository:
    repo: "{{ item.value }}"
    state: present
  loop: "{{ postgresql_ext_extra_packages.apt_repositories | default({}) | dict2items }}"
  when:
    - postgresql_ext_extra_packages is defined
    - ansible_os_family == "Debian"

- name: PostgreSQL | Extensions | Add repos | RHEL
  ansible.builtin.yum_repository:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    baseurl: "{{ item.value.url }}"
    gpgkey: "{{ item.value.gpgkey }}"
    enabled: yes
  loop: "{{ postgresql_ext_extra_packages.yum_repositories | default({}) | dict2items }}"
  when:
    - postgresql_ext_extra_packages is defined
    - ansible_os_family == "RedHat"

# packages

- name: PostgreSQL | Extensions | Add packages | apt
  ansible.builtin.apt:
    name: "{{ postgresql_ext_extra_packages.names }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when:
    - postgresql_ext_extra_packages is defined
    - ansible_os_family == "Debian"

- name: PostgreSQL | Extensions | Add packages | RHEL
  ansible.builtin.yum:
    name: "{{ postgresql_ext_extra_packages.names }}"
    state: present
    update_cache: yes
  when:
    - postgresql_ext_extra_packages is defined
    - ansible_os_family == "RedHat"
