---
# file: postgresql/tasks/main.yml

- name: Load OS specific vars from vars files
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- name: Load PostgreSQL version specific variables from vars files
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "../vars/postgresql_{{ postgresql_version }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- ansible.builtin.import_tasks: install_apt.yml
  when: ansible_pkg_mgr == "apt"
  tags: [postgresql, postgresql-install]

- ansible.builtin.import_tasks: install_rhel.yml
  when:
    - (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf")
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux" or ansible_distribution == "Rocky")
  tags: [postgresql, postgresql-install]

- ansible.builtin.import_tasks: install_fedora.yml
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Fedora"
  tags: [postgresql, postgresql-install]

- ansible.builtin.import_tasks: extensions.yml
  tags: [postgresql, postgresql-extensions]

- ansible.builtin.import_tasks: fdw.yml
  tags: [postgresql, postgresql-fdw]

- ansible.builtin.import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- ansible.builtin.import_tasks: users.yml
  tags: [postgresql, postgresql-users]

- ansible.builtin.import_tasks: databases.yml
  tags: [postgresql, postgresql-databases]

- ansible.builtin.import_tasks: schemas.yml
  tags: [postgresql, postgresql-schemas]

- ansible.builtin.import_tasks: users_privileges.yml
  tags: [postgresql, postgresql-users]

- ansible.builtin.import_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: [postgresql, postgresql-monit]

- ansible.builtin.import_tasks: check_pg_version_mismatch.yml
  tags: [postgresql, postgresql-version-mismatch]
