---
# file: postgresql/tasks/monit.yml

- name: PostgreSQL | (Monit) Copy the postgresql monit service file
  ansible.builtin.template:
    src: etc_monit_conf.d_postgresql.j2
    dest: /etc/monit/conf.d/postgresql
