---
# file: tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Make sure the PostgreSQL users are present
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    login_host: "{{ item.host | default(omit) }}"
    port: "{{ postgresql_port }}"
    login_user: "{{postgresql_admin_user}}"
    state: "{{ item.state | default('present') }}"
  no_log: "{{ postgresql_hide_passwords }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_users }}"
  when: postgresql_users|length > 0
